#spring.application.name=test1
spring:
  kafka:
    bootstrap-servers: 192.168.0.12:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: "jissss"
      auto-offset-reset: earliest
server:
  port: 8081